/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.CaseRecord;
import model.Evidence;
import service.DataManager;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Basil
 */
public class PersonDetailFrame extends javax.swing.JFrame {
    private CaseRecord caseRecord;
    /**
     * Creates new form PersonListFrame
     */
    public PersonDetailFrame(CaseRecord caseRecord) {
        initComponents();
        this.caseRecord = caseRecord;

        tampilDetail();
        tampilEvidence();
        tampilCatatan();
    }
    
    private void tampilDetail() {
    lblId.setText("ID : " + caseRecord.getPerson().getId());

    lblNama.setText("Nama : " + caseRecord.getPerson().getNama());

    lblUmur.setText("Umur : " + caseRecord.getPerson().getUmur());

    lblLokasi.setText(
        "Lokasi Terakhir : " +
        caseRecord.getPerson().getLokasiTerakhir()
    );

    lblCiri.setText(
        "Ciri-ciri : " +
        caseRecord.getPerson().getCiriCiri()
    );

    lblStatus.setText(
        "Status : " +
        caseRecord.getPerson().getStatus()
    );
    String path = caseRecord.getPerson().getFotoPath();

    if (path != null && !path.isEmpty()) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(path);

        java.awt.Image img = icon.getImage().getScaledInstance(
            120, 150, java.awt.Image.SCALE_SMOOTH
        );

        lblFotoPreview.setIcon(new javax.swing.ImageIcon(img));
    }
}
    private void tampilEvidence() {
    DefaultTableModel model =
        (DefaultTableModel) tblEvidence.getModel();

    model.setRowCount(0);

    for (Evidence e : caseRecord.getEvidenceList()) {
        model.addRow(new Object[]{
            e.getJenis(),
            e.getDeskripsi()
        });
    }
}
    private void tampilCatatan() {
        txtCatatan.setText("");

        for (String c : caseRecord.getCatatanList()) {
            txtCatatan.append("- " + c + "\n");
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        lblCiri = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblUmur = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblLokasi = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEvidence = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();
        btnAddEvidence = new javax.swing.JButton();
        lblJudulCatatan = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCatatan = new javax.swing.JTextArea();
        btnAddNote = new javax.swing.JButton();
        btnChangeStatus = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblFotoPreview = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("Detail Data");

        lblCiri.setText("Ciri-ciri");

        lblStatus.setText("Status");

        lblId.setText("ID");

        lblUmur.setText("Umur");

        lblNama.setText("Nama");

        lblLokasi.setText("Lokasi Terakhir");

        tblEvidence.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Jenis", "Deskripsi"
            }
        ));
        jScrollPane2.setViewportView(tblEvidence);

        btnAddEvidence.setText("[ Add Evidence ]");
        btnAddEvidence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEvidenceActionPerformed(evt);
            }
        });

        lblJudulCatatan.setText("Catatan");

        txtCatatan.setColumns(20);
        txtCatatan.setRows(5);
        jScrollPane3.setViewportView(txtCatatan);

        btnAddNote.setText("[ Add Note ]");
        btnAddNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNoteActionPerformed(evt);
            }
        });

        btnChangeStatus.setText("[ Change Notes ]");
        btnChangeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeStatusActionPerformed(evt);
            }
        });

        btnBack.setText("[ Back ]");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblFotoPreview.setText("Preview Foto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddNote)
                                .addGap(42, 42, 42)
                                .addComponent(btnChangeStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                                .addComponent(btnBack))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLokasi)
                                    .addComponent(lblCiri)
                                    .addComponent(lblStatus)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddEvidence)
                                    .addComponent(lblJudulCatatan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFotoPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(lblFotoPreview))
                .addGap(26, 26, 26)
                .addComponent(lblId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUmur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLokasi)
                .addGap(9, 9, 9)
                .addComponent(lblCiri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddEvidence)
                .addGap(31, 31, 31)
                .addComponent(lblJudulCatatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNote)
                    .addComponent(btnChangeStatus)
                    .addComponent(btnBack))
                .addContainerGap())
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEvidenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEvidenceActionPerformed
        String jenis = javax.swing.JOptionPane.showInputDialog(
            this,
            "Jenis Evidence"
        );

        String deskripsi = javax.swing.JOptionPane.showInputDialog(
            this,
            "Deskripsi Evidence"
        );

        if (jenis != null && deskripsi != null) {
            caseRecord.addEvidence(
                new Evidence(jenis, deskripsi)
        );
        DataManager.saveData();

        tampilEvidence();
        }
    }//GEN-LAST:event_btnAddEvidenceActionPerformed

    private void btnAddNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNoteActionPerformed
        String note = javax.swing.JOptionPane.showInputDialog(
            this,
            "Masukkan Catatan"
        );

        if (note != null && !note.isEmpty()) {
            caseRecord.addCatatan(note);
            DataManager.saveData();
            tampilCatatan();
            
        }
    }//GEN-LAST:event_btnAddNoteActionPerformed

    private void btnChangeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeStatusActionPerformed
        String status = javax.swing.JOptionPane.showInputDialog(
            this,
            "Masukkan Status Baru"
        );

        if (status != null && !status.isEmpty()) {
            caseRecord.getPerson().setStatus(status);
            DataManager.saveData();

            tampilDetail();
        }
    }//GEN-LAST:event_btnChangeStatusActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonDetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new PersonDetailFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEvidence;
    private javax.swing.JButton btnAddNote;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChangeStatus;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCiri;
    private javax.swing.JLabel lblFotoPreview;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblJudulCatatan;
    private javax.swing.JLabel lblLokasi;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUmur;
    private javax.swing.JTable tblEvidence;
    private javax.swing.JTextArea txtCatatan;
    // End of variables declaration//GEN-END:variables
}
