/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

import model.CaseRecord;
import model.Person;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

import service.DataManager;

/**
 *
 * @author Basil
 */
public class PersonListFrame extends javax.swing.JFrame {
    private String tipe;

    /**
     * Creates new form PersonDetailFrame
     */
    public PersonListFrame(String tipe) {
        initComponents();
        setSize(900, 550);
        setLocationRelativeTo(null);
        setResizable(false);
        listPanel.setLayout(new javax.swing.BoxLayout(listPanel, javax.swing.BoxLayout.Y_AXIS));
        this.tipe = tipe;

        getContentPane().setBackground(new java.awt.Color(41, 0, 0));
        listPanel.setBackground(new java.awt.Color(41, 0, 0));
        jScrollPane2.getViewport().setBackground(new java.awt.Color(41, 0, 0));
        jScrollPane2.setBorder(null);

        lblPageTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/title1.gif")));
        lblPageTitle.setText(tipe.equals("missing") ? " - Missing Person" : " - Buronan");
        lblPageTitle.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        lblPageTitle.setForeground(java.awt.Color.WHITE);

        lblSearch.setForeground(java.awt.Color.WHITE);

        btnSearch.setBackground(new java.awt.Color(80, 0, 0));
        btnSearch.setForeground(java.awt.Color.WHITE);
        btnCreate.setBackground(new java.awt.Color(80, 0, 0));
        btnCreate.setForeground(java.awt.Color.WHITE);
        btnRefresh.setBackground(new java.awt.Color(80, 0, 0));
        btnRefresh.setForeground(java.awt.Color.WHITE);
        btnBack.setBackground(new java.awt.Color(80, 0, 0));
        btnBack.setForeground(java.awt.Color.WHITE);

        tampilData(DataManager.getList(tipe));
    }

    private void tampilData(ArrayList<CaseRecord> list) {
        listPanel.removeAll();
        listPanel.setAlignmentY(java.awt.Component.TOP_ALIGNMENT);

        for (CaseRecord c : list) {
            Person p = c.getPerson();

            javax.swing.JPanel card = new javax.swing.JPanel();
            card.setLayout(new java.awt.BorderLayout(10, 10));
            card.setPreferredSize(new java.awt.Dimension(610, 120));
            card.setMaximumSize(new java.awt.Dimension(610, 120));
            card.setBackground(new java.awt.Color(55, 0, 0));
            card.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(80, 0, 0)));

            javax.swing.JLabel lblFoto = new javax.swing.JLabel();
            lblFoto.setPreferredSize(new java.awt.Dimension(100, 100));

            if (p.getFotoPath() != null && !p.getFotoPath().isEmpty()) {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(p.getFotoPath());
                java.awt.Image img = icon.getImage().getScaledInstance(
                        90, 90, java.awt.Image.SCALE_SMOOTH);
                lblFoto.setIcon(new javax.swing.ImageIcon(img));
            }

            javax.swing.JLabel lblNama = new javax.swing.JLabel(p.getNama());
            lblNama.setForeground(java.awt.Color.WHITE);
            lblNama.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

            javax.swing.JLabel lblStatus = new javax.swing.JLabel(p.getStatus());
            lblStatus.setForeground(new java.awt.Color(220, 220, 220));

            javax.swing.JLabel lblLokasi = new javax.swing.JLabel(p.getLokasiTerakhir());
            lblLokasi.setForeground(new java.awt.Color(200, 200, 200));

            javax.swing.JPanel panelText = new javax.swing.JPanel();
            panelText.setLayout(new javax.swing.BoxLayout(panelText, javax.swing.BoxLayout.Y_AXIS));
            panelText.setBackground(new java.awt.Color(55, 0, 0));
            panelText.add(lblNama);
            panelText.add(lblStatus);
            panelText.add(lblLokasi);

            javax.swing.JButton btnDetail = new javax.swing.JButton("Open Detail");
            btnDetail.setPreferredSize(new java.awt.Dimension(120, 30));
            btnDetail.setBackground(new java.awt.Color(80, 0, 0));
            btnDetail.setForeground(java.awt.Color.WHITE);

            btnDetail.addActionListener(e -> {
                new PersonDetailFrame(c).setVisible(true);
            });

            card.add(lblFoto, java.awt.BorderLayout.WEST);
            card.add(panelText, java.awt.BorderLayout.CENTER);
            card.add(btnDetail, java.awt.BorderLayout.EAST);

            listPanel.add(card);
        }

        listPanel.revalidate();
        listPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPageTitle = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPageTitle.setText("Missing Person");

        lblSearch.setText("Search Name :");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnCreate.setText("[ Create New ]");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        listPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listPanel.setLayout(new javax.swing.BoxLayout(listPanel, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane2.setViewportView(listPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(lblPageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 350,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(89, 89, 89)
                                                .addComponent(lblSearch)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 83,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(259, 259, 259)
                                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnCreate)
                                                                .addGap(50, 50, 50)
                                                                .addComponent(btnRefresh)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(btnBack))
                                                        .addComponent(jScrollPane2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 666,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(740, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblPageTitle)
                                                        .addComponent(lblSearch)
                                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnSearch))
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane2)
                                                .addGap(78, 78, 78))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(318, Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnCreate)
                                                        .addComponent(btnRefresh)
                                                        .addComponent(btnBack))))
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRefreshActionPerformed
        tampilData(DataManager.getList(tipe));
    }// GEN-LAST:event_btnRefreshActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSearchActionPerformed
        String keyword = txtSearch.getText();
        tampilData(DataManager.search(tipe, keyword));
    }// GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
        dispose();
    }// GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCreateActionPerformed
        new PersonFormFrame(tipe).setVisible(true);
    }// GEN-LAST:event_btnCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonListFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonListFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonListFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonListFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonListFrame("missing").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPageTitle;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JPanel listPanel;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
